

import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { About, Main, Skills,Projects } from '../src/components'

const inter = Inter({ subsets: ['latin'] })






export default function Home(props) {
  const {data} = props;
  return (
    <div >
      <Head>
        <title>marcuoware</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className='block md:mx-auto dark:bg-slate-900' >
        <section className='min-h-screen'>
          <Main/>
          <About/>
          <Skills/>
          <Projects data={data}/>

        </section>
      </main>
    </div>
  )
}


async function getServerSideProps(){
  const {data} = await import('/data/data.js');
  return {props:{data}};
}
